apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
  namespace: rhbk-mc
type: Opaque
stringData:
  username: keycloak # notsecret
  password: "KeycloakPoC2026!" # notsecret
---
# Self-signed TLS for PoC (regenerate with scripts/gen-tls-secret.sh if needed)
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-tls-secret
  namespace: rhbk-mc
type: kubernetes
data:
  tls.crt: ""
  tls.key: ""
