listen_addresses = '*'
port = 5432
wal_level = replica
max_wal_senders = 10
max_replication_slots = 10
hot_standby = on
synchronous_commit = on
synchronous_standby_names = 'FIRST 1 (site_b_standby)'
wal_keep_size = 1GB
password_encryption = scram-sha-256
